apiVersion: apps/v1
kind: Deployment
metadata:
  name: commands-deployment
spec:
  selector:
    matchLabels:
      app: commands
  template:
    metadata:
      labels:
        app: commands
    spec:
      containers:
      - name: commands
        image: janitha000/commands:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDbSettings__Port
            value: mongodb-service
          - name: MongoDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: commands-secret
                key: mongodb-password
        livenessProbe:
          httpGet: 
            path: /health/live
            port: 80
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 80
